//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zenonApi.Core.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComparisonValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComparisonValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zenonApi.Core.Tests.ComparisonValues", typeof(ComparisonValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;TestConverterSerializationConverterUsage SimpleInteger=&quot;Test + 5&quot;&gt;
        ///   &lt;SimpleDouble&gt;5.25&lt;/SimpleDouble&gt;
        ///   &lt;SimpleString&gt;HelloWorld&lt;/SimpleString&gt;
        ///&lt;/TestConverterSerializationConverterUsage&gt;.
        /// </summary>
        internal static string ConverterFunctionalityTest {
            get {
                return ResourceManager.GetString("ConverterFunctionalityTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ListHandlingOnSingleNodesClass&gt;
        ///   &lt;SimpleInteger&gt;123&lt;/SimpleInteger&gt;
        ///&lt;/ListHandlingOnSingleNodesClass&gt;.
        /// </summary>
        internal static string EncapsulateChildsOnNonListEntity {
            get {
                return ResourceManager.GetString("EncapsulateChildsOnNonListEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;EnumSerializationAsNodeClass&gt;
        ///   &lt;SimpleInteger&gt;1234&lt;/SimpleInteger&gt;
        ///   &lt;SimpleEnumSerializationEnum&gt;AbcTest&lt;/SimpleEnumSerializationEnum&gt;
        ///&lt;/EnumSerializationAsNodeClass&gt;.
        /// </summary>
        internal static string EnumSerializationAsNode {
            get {
                return ResourceManager.GetString("EnumSerializationAsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;EnumSerializationAsParameterClass SimpleEnumSerializationEnum=&quot;AbcTest&quot;&gt;
        ///   &lt;SimpleInteger&gt;1234&lt;/SimpleInteger&gt;
        ///&lt;/EnumSerializationAsParameterClass&gt;.
        /// </summary>
        internal static string EnumSerializationAsParameter {
            get {
                return ResourceManager.GetString("EnumSerializationAsParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ListHandlingComplexListEncapsulateChildsIfListFalse&gt;
        ///   &lt;PrimitiveList&gt;
        ///      &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///      &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///      &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///   &lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;
        ///      &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///      &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///      &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///   &lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;
        ///      &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListHandlingComplexListEncapsulateChildsIfListFalse {
            get {
                return ResourceManager.GetString("ListHandlingComplexListEncapsulateChildsIfListFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ListHandlingComplexListEncapsulateChildsIfListTrue&gt;
        ///   &lt;PrimitiveList&gt;
        ///      &lt;SimpleSingleSerializationClass&gt;
        ///         &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///         &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///         &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///      &lt;/SimpleSingleSerializationClass&gt;
        ///      &lt;SimpleSingleSerializationClass&gt;
        ///         &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///         &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///         &lt;SimpleString&gt;TestString&lt;/Sim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListHandlingComplexListEncapsulateChildsIfListTrue {
            get {
                return ResourceManager.GetString("ListHandlingComplexListEncapsulateChildsIfListTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ListHandlingDoublePrimitiveListEncapsulateChildsIfListFalse&gt;
        ///   &lt;PrimitiveList&gt;1.1&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;2.2&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;3.3&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;4.4&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;5.5&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;6.6&lt;/PrimitiveList&gt;
        ///&lt;/ListHandlingDoublePrimitiveListEncapsulateChildsIfListFalse&gt;.
        /// </summary>
        internal static string ListHandlingDoublePrimitiveListEncapsulateChildsIfListFalse {
            get {
                return ResourceManager.GetString("ListHandlingDoublePrimitiveListEncapsulateChildsIfListFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ListHandlingDoublePrimitiveListEncapsulateChildsIfListTrue&gt;
        ///   &lt;PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;1.1&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;2.2&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;3.3&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;4.4&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;5.5&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;6.6&lt;/PrimitiveList&gt;
        ///   &lt;/PrimitiveList&gt;
        ///&lt;/ListHandlingDoublePrimitiveListEncapsulateChildsIfListTrue&gt;.
        /// </summary>
        internal static string ListHandlingDoublePrimitiveListEncapsulateChildsIfListTrue {
            get {
                return ResourceManager.GetString("ListHandlingDoublePrimitiveListEncapsulateChildsIfListTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ListHandlingIntegerPrimitiveListEncapsulateChildsIfListFalse&gt;
        ///   &lt;PrimitiveList&gt;1&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;2&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;3&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;4&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;5&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;6&lt;/PrimitiveList&gt;
        ///&lt;/ListHandlingIntegerPrimitiveListEncapsulateChildsIfListFalse&gt;.
        /// </summary>
        internal static string ListHandlingIntegerPrimitiveListEncapsulateChildsIfListFalse {
            get {
                return ResourceManager.GetString("ListHandlingIntegerPrimitiveListEncapsulateChildsIfListFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ListHandlingIntegerPrimitiveListEncapsulateChildsIfListTrue&gt;
        ///   &lt;PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;1&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;2&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;3&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;4&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;5&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;6&lt;/PrimitiveList&gt;
        ///   &lt;/PrimitiveList&gt;
        ///&lt;/ListHandlingIntegerPrimitiveListEncapsulateChildsIfListTrue&gt;.
        /// </summary>
        internal static string ListHandlingIntegerPrimitiveListEncapsulateChildsIfListTrue {
            get {
                return ResourceManager.GetString("ListHandlingIntegerPrimitiveListEncapsulateChildsIfListTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ListHandlingStringPrimitiveListEncapsulateChildsIfListFalse&gt;
        ///   &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///   &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///&lt;/ListHandlingStringPrimitiveListEncapsulateChildsIfListFalse&gt;.
        /// </summary>
        internal static string ListHandlingStringPrimitiveListEncapsulateChildsIfListFalse {
            get {
                return ResourceManager.GetString("ListHandlingStringPrimitiveListEncapsulateChildsIfListFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ListHandlingStringPrimitiveListEncapsulateChildsIfListTrue&gt;
        ///   &lt;PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///      &lt;PrimitiveList&gt;a&lt;/PrimitiveList&gt;
        ///   &lt;/PrimitiveList&gt;
        ///&lt;/ListHandlingStringPrimitiveListEncapsulateChildsIfListTrue&gt;.
        /// </summary>
        internal static string ListHandlingStringPrimitiveListEncapsulateChildsIfListTrue {
            get {
                return ResourceManager.GetString("ListHandlingStringPrimitiveListEncapsulateChildsIfListTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;MixedClass EnumSerializationEnum=&quot;AbcTest&quot;&gt;
        ///   &lt;EnumSerializationAttrEnum&gt;AbcTest&lt;/EnumSerializationAttrEnum&gt;
        ///   &lt;SimpleSingleSerializationEncapsulateTrueClasses&gt;
        ///      &lt;SimpleSingleSerializationEncapsulateTrueClasses_0 SimpleAttrInteger=&quot;8&quot; SimpleAttrDouble=&quot;8.88&quot; SimpleAttrString=&quot;HelloWorld&quot;&gt;
        ///         &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///         &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///         &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///      &lt;/SimpleSin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mixed {
            get {
                return ResourceManager.GetString("Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NestedSerializationWithAttributes SimpleAttrInteger=&quot;8&quot; SimpleAttrDouble=&quot;8.88&quot; SimpleAttrString=&quot;HelloWorld&quot;&gt;
        ///   &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///   &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///   &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///   &lt;SimpleSerializationWithAttributes SimpleAttrInteger=&quot;8&quot; SimpleAttrDouble=&quot;8.88&quot; SimpleAttrString=&quot;HelloWorld&quot;&gt;
        ///      &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///      &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///      &lt;SimpleString&gt;TestStri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NestedSerializationWithAttributes {
            get {
                return ResourceManager.GetString("NestedSerializationWithAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Test&gt;
        ///   &lt;NodeNotNull&gt;5&lt;/NodeNotNull&gt;
        ///   &lt;AttributeNotNull&gt;5&lt;/AttributeNotNull&gt;
        ///   &lt;NodeEnumNotNull&gt;value_b&lt;/NodeEnumNotNull&gt;
        ///   &lt;AttributeEnumNotNull&gt;value_b&lt;/AttributeEnumNotNull&gt;
        ///&lt;/Test&gt;.
        /// </summary>
        internal static string NullablePrimitives {
            get {
                return ResourceManager.GetString("NullablePrimitives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Test&gt;
        ///   &lt;DefaultList1&gt;1&lt;/DefaultList1&gt;
        ///   &lt;DefaultList1&gt;2&lt;/DefaultList1&gt;
        ///   &lt;DefaultList1&gt;3&lt;/DefaultList1&gt;
        ///   &lt;NestedList1&gt;
        ///      &lt;NestedList1&gt;1&lt;/NestedList1&gt;
        ///      &lt;NestedList1&gt;2&lt;/NestedList1&gt;
        ///      &lt;NestedList1&gt;3&lt;/NestedList1&gt;
        ///   &lt;/NestedList1&gt;
        ///   &lt;DefaultList2&gt;value_a&lt;/DefaultList2&gt;
        ///   &lt;DefaultList2&gt;value_b&lt;/DefaultList2&gt;
        ///   &lt;DefaultList2&gt;value_c&lt;/DefaultList2&gt;
        ///   &lt;NestedList2&gt;
        ///      &lt;NestedList2&gt;value_a&lt;/NestedList2&gt;
        ///      &lt;NestedL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NullablesInList {
            get {
                return ResourceManager.GetString("NullablesInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;OmitComplexWithOmitClass&gt;
        ///   &lt;SimpleSingleSerializationClass&gt;
        ///      &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///      &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///      &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///   &lt;/SimpleSingleSerializationClass&gt;
        ///&lt;/OmitComplexWithOmitClass&gt;.
        /// </summary>
        internal static string OmitComplexWithOmit {
            get {
                return ResourceManager.GetString("OmitComplexWithOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;OmitComplexWithoutOmitClass&gt;
        ///   &lt;SimpleSingleSerializationClass&gt;
        ///      &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///      &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///      &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///   &lt;/SimpleSingleSerializationClass&gt;
        ///   &lt;NullSimpleSingleSerializationClass /&gt;
        ///&lt;/OmitComplexWithoutOmitClass&gt;.
        /// </summary>
        internal static string OmitComplexWithoutOmit {
            get {
                return ResourceManager.GetString("OmitComplexWithoutOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;OmitPrimitivesWithOmitClass&gt;
        ///   &lt;SimpleInteger&gt;12&lt;/SimpleInteger&gt;
        ///&lt;/OmitPrimitivesWithOmitClass&gt;.
        /// </summary>
        internal static string OmitPrimitivesWithOmit {
            get {
                return ResourceManager.GetString("OmitPrimitivesWithOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;OmitPrimitivesWithoutOmitClass&gt;
        ///   &lt;NullInteger /&gt;
        ///   &lt;SimpleInteger&gt;12&lt;/SimpleInteger&gt;
        ///&lt;/OmitPrimitivesWithoutOmitClass&gt;.
        /// </summary>
        internal static string OmitPrimitivesWithoutOmit {
            get {
                return ResourceManager.GetString("OmitPrimitivesWithoutOmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ResolverOnNodesThatAreNotListsClass&gt;
        ///   &lt;SimpleInteger_0&gt;abc&lt;/SimpleInteger_0&gt;
        ///   &lt;SimpleDouble_0&gt;hij&lt;/SimpleDouble_0&gt;
        ///   &lt;SimpleString&gt;def&lt;/SimpleString&gt;
        ///&lt;/ResolverOnNodesThatAreNotListsClass&gt;.
        /// </summary>
        internal static string ResolverOnNodesThatAreNotLists {
            get {
                return ResourceManager.GetString("ResolverOnNodesThatAreNotLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ResolverThatReturnsPropertyInfoTypeClass&gt;
        ///   &lt;SimpleInteger_0&gt;abc&lt;/SimpleInteger_0&gt;
        ///   &lt;SimpleInteger_1&gt;def&lt;/SimpleInteger_1&gt;
        ///   &lt;SimpleInteger_2&gt;hij&lt;/SimpleInteger_2&gt;
        ///&lt;/ResolverThatReturnsPropertyInfoTypeClass&gt;.
        /// </summary>
        internal static string ResolverThatReturnsPropertyInfoType {
            get {
                return ResourceManager.GetString("ResolverThatReturnsPropertyInfoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SelectiveNodeOrderingClass&gt;
        ///   &lt;SimpleString&gt;Abc&lt;/SimpleString&gt;
        ///   &lt;SimpleDouble&gt;88.88&lt;/SimpleDouble&gt;
        ///   &lt;SimpleInteger&gt;12&lt;/SimpleInteger&gt;
        ///&lt;/SelectiveNodeOrderingClass&gt;.
        /// </summary>
        internal static string SelectiveNodeOrdering {
            get {
                return ResourceManager.GetString("SelectiveNodeOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SimpleAttributeOrderingClass SimpleAttrInteger=&quot;12&quot; SimpleAttrString=&quot;Abc&quot; SimpleAttrDouble=&quot;88.88&quot;&gt;
        ///   &lt;SimpleDouble&gt;88.88&lt;/SimpleDouble&gt;
        ///   &lt;SimpleString&gt;Abc&lt;/SimpleString&gt;
        ///   &lt;SimpleInteger&gt;12&lt;/SimpleInteger&gt;
        ///&lt;/SimpleAttributeOrderingClass&gt;.
        /// </summary>
        internal static string SimpleAttributeOrdering {
            get {
                return ResourceManager.GetString("SimpleAttributeOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SimpleNodeOrderingClass&gt;
        ///   &lt;SimpleDouble&gt;88.88&lt;/SimpleDouble&gt;
        ///   &lt;SimpleString&gt;Abc&lt;/SimpleString&gt;
        ///   &lt;SimpleInteger&gt;12&lt;/SimpleInteger&gt;
        ///&lt;/SimpleNodeOrderingClass&gt;.
        /// </summary>
        internal static string SimpleNodeOrdering {
            get {
                return ResourceManager.GetString("SimpleNodeOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SimpleNodeOrderingDuplicateOrderNumbersClass&gt;
        ///   &lt;SimpleDouble&gt;88.88&lt;/SimpleDouble&gt;
        ///   &lt;SimpleString&gt;Abc&lt;/SimpleString&gt;
        ///   &lt;SimpleInteger&gt;12&lt;/SimpleInteger&gt;
        ///&lt;/SimpleNodeOrderingDuplicateOrderNumbersClass&gt;.
        /// </summary>
        internal static string SimpleNodeOrderingDuplicateOrderNumbers {
            get {
                return ResourceManager.GetString("SimpleNodeOrderingDuplicateOrderNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SimpleSerializationWithAttributesClass SimpleAttrInteger=&quot;8&quot; SimpleAttrDouble=&quot;8.88&quot; SimpleAttrString=&quot;HelloWorld&quot;&gt;
        ///   &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///   &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///   &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///&lt;/SimpleSerializationWithAttributesClass&gt;.
        /// </summary>
        internal static string SimpleSerializationWithAttributesToString {
            get {
                return ResourceManager.GetString("SimpleSerializationWithAttributesToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SimpleSingleSerializationClass&gt;
        ///   &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///   &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///   &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///&lt;/SimpleSingleSerializationClass&gt;.
        /// </summary>
        internal static string SimpleSingleSerializationToString {
            get {
                return ResourceManager.GetString("SimpleSingleSerializationToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;StatusEnumClass&gt;
        ///   &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///   &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///   &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///&lt;/StatusEnumClass&gt;.
        /// </summary>
        internal static string StatusEnum {
            get {
                return ResourceManager.GetString("StatusEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NestedSerializationNodes&gt;
        ///   &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///   &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///   &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///   &lt;SimpleSingleSerialization&gt;
        ///      &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///      &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///      &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///   &lt;/SimpleSingleSerialization&gt;
        ///&lt;/NestedSerializationNodes&gt;.
        /// </summary>
        internal static string TestNestedSerializationNodes {
            get {
                return ResourceManager.GetString("TestNestedSerializationNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Test UnknownTopLevel=&quot;123&quot;&gt;
        ///   &lt;KnownEntity Unknown1=&quot;Hello&quot; KnownValue=&quot;5&quot; Unknown2=&quot;World&quot; /&gt;
        ///   &lt;KnownEntity KnownValue=&quot;5&quot; Unknown1=&quot;Hello&quot; Unknown2=&quot;World&quot; /&gt;
        ///   &lt;KnownEntity Unknown1=&quot;Hello&quot; Unknown2=&quot;World&quot; KnownValue=&quot;5&quot; /&gt;
        ///   &lt;KnownEntity KnownValue=&quot;5&quot; /&gt;
        ///&lt;/Test&gt;.
        /// </summary>
        internal static string UnknownAttributes {
            get {
                return ResourceManager.GetString("UnknownAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Test&gt;
        ///   &lt;KnownEntity KnownAttribute=&quot;18&quot;&gt;
        ///      &lt;KnownNode&gt;17&lt;/KnownNode&gt;
        ///   &lt;/KnownEntity&gt;
        ///   &lt;KnownEntity KnownAttribute=&quot;20&quot;&gt;
        ///      &lt;KnownNode&gt;19&lt;/KnownNode&gt;
        ///	  UnknownContent2
        ///   &lt;/KnownEntity&gt;
        ///   &lt;OtherKnownEntity KnownAttribute=&quot;22&quot; UnknownAttribute1=&quot;1&quot;&gt;
        ///      &lt;KnownNode UnknownAttribute2=&quot;2&quot;&gt;21&lt;/KnownNode&gt;
        ///   &lt;/OtherKnownEntity&gt;
        ///   UnknownContent1
        ///&lt;/Test&gt;.
        /// </summary>
        internal static string UnknownContent {
            get {
                return ResourceManager.GetString("UnknownContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Test&gt;
        ///   &lt;KnownEntity&gt;5&lt;/KnownEntity&gt;
        ///   &lt;UnknownSingle&gt;5.3&lt;/UnknownSingle&gt;
        ///   &lt;UnknownMultiple&gt;TestString1&lt;/UnknownMultiple&gt;
        ///   &lt;UnknownMultiple&gt;TestString2&lt;/UnknownMultiple&gt;
        ///   &lt;UnknownNested&gt;
        ///      &lt;SimpleInteger&gt;5&lt;/SimpleInteger&gt;
        ///      &lt;SimpleDouble&gt;5.3&lt;/SimpleDouble&gt;
        ///      &lt;SimpleString&gt;TestString&lt;/SimpleString&gt;
        ///   &lt;/UnknownNested&gt;
        ///&lt;/Test&gt;.
        /// </summary>
        internal static string UnknownNodes {
            get {
                return ResourceManager.GetString("UnknownNodes", resourceCulture);
            }
        }
    }
}
