//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zenonApi.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zenonApi.Logic.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format for {0} type. Format {1} not valid..
        /// </summary>
        internal static string DimensionTypeInvalidFormat {
            get {
                return ResourceManager.GetString("DimensionTypeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format for variable dimensions. Zero-sized dimensions are only allowed if all dimension parts are zero, or if they occur after a non-zero-sized entry..
        /// </summary>
        internal static string ErrorMessageDimensionsInvalidDatatype {
            get {
                return ResourceManager.GetString("ErrorMessageDimensionsInvalidDatatype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum supported dimension are 3..
        /// </summary>
        internal static string ErrorMessageDimensionsOutOfRange {
            get {
                return ResourceManager.GetString("ErrorMessageDimensionsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} must not be null or consist solely of white space characters..
        /// </summary>
        internal static string ErrorMessageParameterIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ErrorMessageParameterIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse a dimension definition from {0}. Expected positive numeric numbers in the format &quot;x,y,z&quot;..
        /// </summary>
        internal static string ErrorMessageParsingDimensionsFailed {
            get {
                return ResourceManager.GetString("ErrorMessageParsingDimensionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while initializing ini file. File not found at: {0}.
        /// </summary>
        internal static string IniFileNotFoundException {
            get {
                return ResourceManager.GetString("IniFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid constructor call of type {0}. The specified path must belong to a K5DBXS.INI file..
        /// </summary>
        internal static string K5DbxsIniFileConstructorInvalidDataException {
            get {
                return ResourceManager.GetString("K5DbxsIniFileConstructorInvalidDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid constructor call of type {0}. Argument of constructor cannot be null or whitespace..
        /// </summary>
        internal static string LogicDefinesConstructorArgumentException {
            get {
                return ResourceManager.GetString("LogicDefinesConstructorArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid constructor call of type {0}. Arguments of constructor cannot be null or whitespace..
        /// </summary>
        internal static string LogicOptionTupleConstructorArgumentException {
            get {
                return ResourceManager.GetString("LogicOptionTupleConstructorArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 255.
        /// </summary>
        internal static string StringVariableDefaultMaxLength {
            get {
                return ResourceManager.GetString("StringVariableDefaultMaxLength", resourceCulture);
            }
        }
    }
}
